### ISSUE TITLE
Ansible config show-and-tell

### ISSUE THREAD

**Issue by webknjaz** [jaraco/dotfiles#1]
Hey @jaraco, I stumbled upon your repo and figured I'd share my Ansible-based configuration for dev userspace. Maybe, you'll find some of it interesting:

* user-global Git config (with all the settings I tend to forget to configure): https://github.com/webknjaz/ansible-gentoo-laptop/blob/9af6f8a/roles/gentoo-userspace/defaults/main.yml#L34-L47
* user-global SSH config: https://github.com/webknjaz/ansible-gentoo-laptop/blob/9af6f8a/roles/gentoo-userspace/defaults/main.yml#L202-L210
* pyenv setup: https://github.com/webknjaz/ansible-gentoo-laptop/blob/9af6f8a/roles/gentoo-userspace/tasks/pyenv.yml

  Config: https://github.com/webknjaz/ansible-gentoo-laptop/blob/9af6f8a/roles/gentoo-userspace/defaults/main.yml#L14-L27
* source code layout https://github.com/webknjaz/ansible-gentoo-laptop/blob/9af6f8a/roles/gentoo-userspace/defaults/main.yml#L218-L668

  This one makes `~/src` the source root, makes `~/src/experiments` for stuff I can throw away safely; it also clones (and synchronizes) the git repo layout for various code hostsing. For example, for github.com, it clones everything as `~/src/github/<owner>/<repo>`, optionally adding a Git remote called `fork` to some.

  Implementation: https://github.com/webknjaz/ansible-gentoo-laptop/blob/9af6f8a/roles/gentoo-userspace/tasks/src.yml

**Comment by jaraco** [comment]
I used to keep a lot of this config in Dropbox and symlink it from the various locations, but when I got started trying to use github.dev (codespaces), I found that the best (only?) way to customize that environment was to have a repo called dotfiles. I actually don't care for dotfiles because it requires all of the config to be in the root of the repo (and not organized by platform or application or other, as I'd done in the past.

Thanks for sharing the ansible approach. It's very interesting and will surely be a great resource should I take on adopting ansible at some point.
